#!/bin/bash

N_ROBOTS=$1

my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!

echo "Launching Stage..."
sleep 2s
roslaunch multirobot_stage multirobot_stage.launch world_file:=willow_multi_robot &
pid="$pid $!"

echo "Launching SLAM stack for $N_ROBOTS robots..."
sleep 2s
for i in `seq 0 $[N_ROBOTS-1]`;
do
  roslaunch multirobot_stage single_slam.launch robot_name:=robot_$i &
  pid="$pid $!"
  sleep 1s
  
  roslaunch multirobot_stage multirobot_static_transform.launch child_ns:=robot_$i dx:=0 dy:=0 &
  pid="$pid $!"
  sleep 1s
  
  roslaunch multirobot_stage single_global_odom_transform.launch robot_name:=robot_$i &
  pid="$pid $!"
  sleep 1s
done

sleep 2s
roslaunch multirobot_stage multirobot_static_transform.launch parent_frame:=world child_ns:=map child_frame:=map dx:="$(rosparam get /robot_0/gmapping/xmax)" dy:="$(rosparam get /robot_0/gmapping/ymax)" &
pid="$pid $!"

# Following nodes split out into run-multi-robot-sim-nav
#echo "Launching navigation stack..."
#sleep 2s
#for i in `seq 0 1`;
#do
#  roslaunch multirobot_stage single_map_merge.launch robot_name:=robot_$i robot_index:=$i&
#  pid="$pid $!"
#  sleep 2s
#  
#  roslaunch multirobot_stage single_navigation.launch robot_name:=robot_$i &
#  pid="$pid $!"
#  sleep 2s
#done

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
