#!/bin/bash

my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!
sleep 5s

echo "Launching Stage..."
roslaunch multirobot_stage multirobot_stage.launch &
pid="$pid $!"
sleep 2s

echo "Launching navigation stack..."
for i in `seq 0 1`;
do
  rosrun cg_mrslam cg_mrslam -idRobot $i -nRobots 2 -baseAddr 127.0.0. -scanTopic base_scan -mapFrame /robot_$i/map -odomFrame /robot_$i/odom -baseFrame /robot_$i/base_link -modality sim -publishMap -publishGraph -o testmrslam.g2o __ns:=robot_$i &
  pid="$pid $!"
  sleep 2s
  
  roslaunch multirobot_stage multirobot_static_transform.launch child_frame:=robot_$i &
  pid="$pid $!"
  sleep 2s

  roslaunch multirobot_stage move_base.launch robot_name:=robot_$i &
  pid="$pid $!"
  sleep 2s
done

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
