#!/bin/bash

my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!
sleep 2s

echo "Launching Stage..."
roslaunch multirobot_stage multirobot_stage.launch world_file:=test_world &
pid="$pid $!"
sleep 2s

echo "Launching navigation stack..."
rosrun gmapping slam_gmapping scan:=base_scan &
pid="$pid $!"
sleep 2s

roslaunch stagebot_2dnav move_base.launch &
pid="$pid $!"
sleep 2s

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
