#!/bin/bash

my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!

echo "Launching Stage..."
sleep 2s
roslaunch multirobot_stage multirobot_stage.launch &
pid="$pid $!"

echo "Launching navigation stack..."
sleep 2s
roslaunch ohm_tsd_slam multi_slam_asl.launch &
pid="$pid $!"
sleep 2s

for i in `seq 0 1`;
do
  roslaunch multirobot_stage move_base.launch robot_name:=robot_$i &
  pid="$pid $!"
  sleep 2s

  roslaunch multirobot_stage multirobot_static_transform.launch child_frame:=robot_$i &
  pid="$pid $!"
  sleep 2s
done

rosservice call /start_stop_slam /robot_0/base_scan 1

rosservice call /start_stop_slam /robot_1/base_scan 1

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
