#!/bin/bash

my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!
sleep 2s

echo "Launching Stage..."
roslaunch multirobot_stage multirobot_stage.launch world_file:=test_world rviz_config:=robot_slam_dyn_obs_stage &
pid="$pid $!"
sleep 2s

echo "Launching navigation stack for robot_0..."
roslaunch nav_bundle single_slam.launch robot_name:=robot_0 &
pid="$pid $!"
sleep 2s

roslaunch multirobot_stage multirobot_static_transform.launch child_frame:=robot_0 &
pid="$pid $!"
sleep 2s

echo "Launching node for robot_1 (dynamic obstacle)..."
roslaunch multirobot_stage bouncer.launch ns:=robot_1 &
pid="$pid $!"

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
