#!/bin/bash

# =========== START ROS simulation nodes =========== 
N_ROBOTS=$1
HEADLESS=$2
if [ $HEADLESS == "1" ]
then
  roslaunch multirobot_stage multirobot_stage_headless.launch &
  pid=$!
  echo "Launching Stage (headless) with $N_ROBOTS robots..."
else
  roslaunch multirobot_stage multirobot_stage.launch &
  pid=$!
  echo "Launching Stage with $N_ROBOTS robots..."
fi

echo "Launching navigation stack..."
sleep 2s
for i in `seq 0 $[N_ROBOTS-1]`;
do
  roslaunch multirobot_stage single_slam.launch robot_name:=robot_$i &
  pid="$pid $!"
  
  #roslaunch multirobot_stage multirobot_static_transform.launch child_frame:=robot_$i &
  #pid="$pid $!"

  roslaunch multirobot_stage multirobot_map_merge.launch robot_name:=robot_$i &
  pid="$pid $!"

  roslaunch multirobot_stage action_node.launch robot_id:=$i &
  pid="$pid $!"
done

roslaunch multirobot_stage rewards_node.launch nRob:=$N_ROBOTS &
pid="$pid $!"

rosrun multirobot_stage comms_node &
pid="$pid $!"

# =========== END ROS simulation nodes =========== 

echo $pid > ~/catkin_ws/src/multirobot_stage/scripts/pid.txt

# =========== START Learning epoch timer ===========
rosparam load $(rospack find multirobot_stage)/scripts/learning_params.yaml
rosrun multirobot_stage learning_episode_timer &

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

